### ISSUE TITLE
Auto-caching existing StateRepository if enabled

### ISSUE THREAD

**Issue by norbson** [togglz/togglz#164]
Current Autoconfiguration support automatic wrapping of StateRepository into CachingStateRepository only if there is no predefined StateRepository.

```java
    @Configuration
    @ConditionalOnMissingBean(StateRepository.class)
    protected static class StateRepositoryConfiguration {
    //some code
            if (properties.getCache().isEnabled()) {
                stateRepository = new CachingStateRepository(stateRepository, properties.getCache().getTimeToLive(), properties.getCache().getTimeUnit());
            }
            return stateRepository;
        }
    }
```

Lets say that I defined JDBCStateRepository on my own and in the same time I set cache properties:
```yaml
togglz:
      cache:
           enabled: true
           time-to-live: 10
           time-unit: seconds
```

I would expect that autoconfiguration wrap my stateRepository into cached one according to above properties.

Regards,
Norbert Krzysztofik
