### ISSUE TITLE
Not possible to configure togglz with yaml file

### ISSUE THREAD

**Issue by taasjord** [togglz/togglz#235]
The /spring-boot-starter documentation, both under Auto configuration and Application Properties, says to use the following to enable feature: 
```
togglz:
  features:
    FOO:
      enabled: true
```
Seems this is incorrect, because it does not work. Instead, as documentation for State Repositories says, the following does work (without 'enabled'):

```
togglz:
  features:
    FOO: true
```
Now I'm not sure if it is the documentation that is wrong or if it was actually supposed to work, but only the latter actually works.

Also spring-boot-starter documentation states that is possible to use properties to create features (without enums as I read it). I don't understand how that could be possible since FeatureManager.isActive only takes a Feature enum and not any string.

Am i misunderstanding something in the documentation here?

**Comment by taasjord** [comment]
Also spring-boot-starter documentation also states that is possible to use properties to _create_ features (without enums as I read it). I don't understand how that could be possible since FeatureManager.isActive only takes a Feature enum and not any string.

**Comment by taasjord** [comment]
Just figured out that the current documentation is for a version that is not released yet, which changes this.

**Comment by taasjord** [comment]
Tried a lot back and forth, and it seems not possible to configure togglz with anything else than just enabled with one yaml file.

This (as documented on togglz.org) does NOT work, enabled is ignored:
```
togglz:
  features:
    MY_FEATURE: 
      enabled: true
      strategy: custom
```

This works (without strategy):
```
togglz:
  features:
    MY_FEATURE: true
```

This does NOT work, invalid yaml:
```
togglz:
  features:
    MY_FEATURE: true
      strategy: custom
```

This does NOT work, invalid yaml:
```
togglz:
  features:
    MY_FEATURE: true
    MY_FEATURE:
      strategy: custom
```

A workaround that looks like it is working now is to split across two yaml files: 

```
application.yml:
togglz:
  features:
    MY_FEATURE:
      strategy: custom

application-<profile>.yml
togglz:
  features:
    MY_FEATURE: true
```

**Comment by taasjord** [comment]
2.4.1.Final, the latest announced on web site.

**Comment by taasjord** [comment]
I coincidentally found this now when browsing through the source: #232, looks like proper support is coming in the next release. But I'm still unsure whether/how yaml is supposed to behave in 2.4.1, since that documentation is maybe overwritten by docs for upcoming 2.5.0.

**Comment by marceloverdijk** [comment]
Yes because of that upcoming change and the docs already pushed we caused some confusion. Sorry for that.

Can you please try this:

```
togglz:
  features:
    MY_FEATURE: true
    MY_FEATURE.strategy: custom
```

I think what should work with `2.4.1`.
