### ISSUE TITLE
Feature configuration with .yml file yields too many features

### ISSUE THREAD

**Issue by dkoding** [togglz/togglz#244]
The following .yml property file...

```
togglz:
  enabled: true
  features:
    MY_FEATURE:
      enabled: true
      strategy: myStrategy
      param:
        Ids: 120,130
```

...creates 3 NamedFeatures in the FeatureManager:

  MY_FEATURE.enabled
  MY_FEATURE.strategy
  MY_FEATURE.param

This is not as expected. I would expect 1 feature in this case.

How to reproduce:

Add the property shown above.
Create a Spring Boot @Config file

    @Bean
    FeatureProvider featureProvider(TogglzProperties properties) {
        Properties props = new Properties();
        props.putAll(properties.getFeatures());
        return new PropertyFeatureProvider(props);
    }

If you debug and look at the 'properties' object you will see the problem.
